apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
namespace: projet-devops
secretGenerator:
- name: mysql-pass
  literals:
  - password=securepassword
resources:
 - mysql-deployment.yaml
 - wordpress-deployment.yaml
 - ingress.yaml